### Reshape Arrays

In [2]:
import numpy as np

In [3]:
matrix = np.array([[1,3,4], [2,5,6], [3,6,7]])

In [4]:
print(matrix.shape)

(3, 3)


In [7]:
matrix.reshape(1,9)

array([[1, 3, 4, 2, 5, 6, 3, 6, 7]])

In [5]:
matrix.reshape(3,5)

ValueError: cannot reshape array of size 9 into shape (3,5)

In [6]:
matrix.reshape(9)

array([1, 3, 4, 2, 5, 6, 3, 6, 7])

### To convert matrix in one dimension

In [8]:
matrix.flatten()

array([1, 3, 4, 2, 5, 6, 3, 6, 7])

### Transpose of Matrix

In [23]:
matrix = np.array([[1,3,4], [2,5,6], [3,6,7]])

In [24]:
matrix

array([[1, 3, 4],
       [2, 5, 6],
       [3, 6, 7]])

In [25]:
matrix.T

array([[1, 2, 3],
       [3, 5, 6],
       [4, 6, 7]])

### Determinant and Rank

In [26]:
np.linalg.det(matrix)

-0.9999999999999991

In [22]:
np.linalg.matrix_rank(matrix)

3

### Diagonal

In [28]:
matrix.diagonal()

array([1, 5, 7])

In [12]:
matrix.diagonal(offset=2)

array([4])

In [30]:
matrix.diagonal(offset= -1)

array([2, 6])

### Trace

In [31]:
matrix.trace()

13

In [32]:
matrix.trace?

Docstring:
a.trace(offset=0, axis1=0, axis2=1, dtype=None, out=None)

Return the sum along diagonals of the array.

Refer to `numpy.trace` for full documentation.

See Also
--------
numpy.trace : equivalent function
Type:      builtin_function_or_method


### Dot Product

In [33]:
matrix = np.array([[1,3,4], [2,5,6], [3,6,7]])

In [34]:
matrix1 = np.array([[1,2,4], [2,5,6], [3,6,7]])

In [35]:
np.dot(matrix, matrix1)

array([[19, 42, 50],
       [30, 67, 80],
       [36, 81, 97]])

### Random Values

In [13]:
np.random.seed(1)

In [20]:
np.random.randint(0,50,4)  #(starting, end, how much)

array([20, 11, 42, 28])

In [51]:
np.random.normal(1.0, 2.0, 10)

array([ 4.48962353, -0.5224138 ,  1.63807819,  0.50125925,  3.92421587,
       -3.12028142,  0.35516559,  0.23189129,  3.26753888, -1.19978253])