# Numpy

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [4]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [5]:
print(type(vector))

<class 'numpy.ndarray'>


In [6]:
vector = np.array([[1],[2],[3]])
print(vector)

[[1]
 [2]
 [3]]


In [7]:
vector = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(vector)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


### Selecting Elements

In [11]:
vector = np.array([1,2,3,4,5,6,7,8,9])

In [12]:
vector[2]

3

In [13]:
vector[:2]

array([1, 2])

In [14]:
vector[-1]

9

### Matrix Slicing

In [3]:
matrix = np.array([[1,2,4], [2,5,1], [3,6,2]])

In [4]:
print(matrix)

[[1 2 4]
 [2 5 1]
 [3 6 2]]


In [6]:
matrix[0,0]

1

In [10]:
print(matrix[0:1, 0:2])

[[1 2]]


In [8]:
matrix[:3, :2]

array([[1, 2],
       [2, 5]])

In [35]:
matrix

array([[1, 2, 4],
       [2, 5, 1],
       [3, 6, 2]])

In [36]:
matrix.shape

(3, 3)

In [37]:
matrix.size

9

In [38]:
matrix.ndim

2

In [39]:
np.max(matrix)

6

In [40]:
np.min(matrix)

1

In [41]:
np.max?

Signature:
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is p

In [42]:
np.max(matrix, axis=0) #columns

array([3, 6, 4])

In [43]:
np.max(matrix, axis=1) #row

array([4, 5, 6])

### Mean, Median, Variace, and SD

In [44]:
#https://github.com/hemansnation

In [45]:
matrix = np.array([[1,2,4], [2,5,1], [3,6,2]])

In [46]:
np.mean(matrix)

2.888888888888889

In [47]:
np.var(matrix)

2.765432098765432

In [48]:
np.std(matrix)

1.6629588385661962